BOT_CONFIG:
  # BOT_CONFIG
  LOG_DEBUG_LEVEL: "$(LOG_DEBUG_LEVEL)"
  LOAD_ACTIONS_FROM_BACKEND: "$(LOAD_ACTIONS_FROM_BACKEND)"

  # PROMPT
  CORE_PROMPT: "$(CORE_PROMPT)"
  MAIN_PROMPT: "$(MAIN_PROMPT)"
  FEEDBACK_GENERAL_BEHAVIOR: "$(FEEDBACK_GENERAL_BEHAVIOR)"

  # COSTS
  SHOW_COST_IN_THREAD: False

  # BOT BEHAVIOR
  REQUIRE_MENTION_NEW_MESSAGE: "$(REQUIRE_MENTION_NEW_MESSAGE)"
  REQUIRE_MENTION_THREAD_MESSAGE: "$(REQUIRE_MENTION_THREAD_MESSAGE)"
  GET_ALL_THREAD_FROM_MESSAGE_LINKS: "$(GET_ALL_THREAD_FROM_MESSAGE_LINKS)"
  MESSAGE_QUEUING_TTL: "$(MESSAGE_QUEUING_TTL)"
  ACTIVATE_MESSAGE_QUEUING: "$(ACTIVATE_MESSAGE_QUEUING)"
  BEGIN_MARKER: "[BEGINIMDETECT]"
  END_MARKER: "[ENDIMDETECT]"
  GET_URL_CONTENT: True
  LLM_CONVERSION_FORMAT: "json"
  BREAK_KEYWORD: "!STOP"
  START_KEYWORD: "!START"
  CLEARQUEUE_KEYWORD: "!CLEARQUEUE"

  # BOT DEFAULT PLUGINS
  ACTION_INTERACTIONS_DEFAULT_PLUGIN_NAME: "$(ACTION_INTERACTIONS_DEFAULT_PLUGIN_NAME)"
  INTERNAL_DATA_PROCESSING_DEFAULT_PLUGIN_NAME: "$(INTERNAL_DATA_PROCESSING_DEFAULT_PLUGIN_NAME)"
  USER_INTERACTIONS_INSTANT_MESSAGING_BEHAVIOR_DEFAULT_PLUGIN_NAME: "$(USER_INTERACTIONS_INSTANT_MESSAGING_BEHAVIOR_DEFAULT_PLUGIN_NAME)"
  GENAI_TEXT_DEFAULT_PLUGIN_NAME: "$(GENAI_TEXT_DEFAULT_PLUGIN_NAME)"
  GENAI_IMAGE_DEFAULT_PLUGIN_NAME: "$(GENAI_IMAGE_DEFAULT_PLUGIN_NAME)"
  GENAI_VECTOR_SEARCH_DEFAULT_PLUGIN_NAME: "$(GENAI_VECTOR_SEARCH_DEFAULT_PLUGIN_NAME)"

UTILS:
  LOGGING:
    LOCAL_LOGGING:
      PLUGIN_NAME: "local_logging"
      LOCAL_LOGGING_FILE_PATH: 'C:\LOGS\GENAI_BOT.log'

    AZURE_LOGGING:
      PLUGIN_NAME: "azure_logging"
      AZURE_LOGGING_APPLICATIONINSIGHTS_CONNECTION_STRING: <your_applicationinsights_connection_string>

PLUGINS:
  ACTION_INTERACTIONS:
    DEFAULT:
      MAIN_ACTIONS:
        PLUGIN_NAME: "main_actions"
    CUSTOM: {}

  BACKEND:
    INTERNAL_DATA_PROCESSING:
      FILE_SYSTEM:
        PLUGIN_NAME: "file_system"
        FILE_SYSTEM_DIRECTORY: "$(FILE_SYSTEM_DIRECTORY)"
        FILE_SYSTEM_SESSIONS_CONTAINER: "$(FILE_SYSTEM_SESSIONS_CONTAINER)"
        FILE_SYSTEM_FEEDBACKS_CONTAINER: "$(FILE_SYSTEM_FEEDBACKS_CONTAINER)"
        FILE_SYSTEM_CONCATENATE_CONTAINER: "$(FILE_SYSTEM_CONCATENATE_CONTAINER)"
        FILE_SYSTEM_PROMPTS_CONTAINER: "$(FILE_SYSTEM_PROMPTS_CONTAINER)"
        FILE_SYSTEM_COSTS_CONTAINER: "$(FILE_SYSTEM_COSTS_CONTAINER)"
        FILE_SYSTEM_PROCESSING_CONTAINER: "$(FILE_SYSTEM_PROCESSING_CONTAINER)"
        FILE_SYSTEM_ABORT_CONTAINER: "$(FILE_SYSTEM_ABORT_CONTAINER)"
        FILE_SYSTEM_VECTORS_CONTAINER: "$(FILE_SYSTEM_VECTORS_CONTAINER)"
        FILE_SYSTEM_CUSTOM_ACTIONS_CONTAINER: "$(FILE_SYSTEM_CUSTOM_ACTIONS_CONTAINER)"
        FILE_SYSTEM_SUBPROMPTS_CONTAINER: "$(FILE_SYSTEM_SUBPROMPTS_CONTAINER)"
        FILE_SYSTEM_MESSAGES_QUEUE_CONTAINER: "$(FILE_SYSTEM_MESSAGES_QUEUE_CONTAINER)"

      #AZURE_BLOB_STORAGE:
      #  PLUGIN_NAME: azure_blob_storage
      #  AZURE_BLOB_STORAGE_CONNECTION_STRING: "$(AZURE_BLOB_STORAGE_CONNECTION_STRING)"
      #  AZURE_BLOB_STORAGE_ABORT_CONTAINER: "$(AZURE_BLOB_STORAGE_ABORT_CONTAINER)"
      #  AZURE_BLOB_STORAGE_CONCATENATE_CONTAINER: "$(AZURE_BLOB_STORAGE_CONCATENATE_CONTAINER)"
      #  AZURE_BLOB_STORAGE_COSTS_CONTAINER: "$(AZURE_BLOB_STORAGE_COSTS_CONTAINER)"
      #  AZURE_BLOB_STORAGE_FEEDBACKS_CONTAINER: "$(AZURE_BLOB_STORAGE_FEEDBACKS_CONTAINER)"
      #  AZURE_BLOB_STORAGE_PROCESSING_CONTAINER: "$(AZURE_BLOB_STORAGE_PROCESSING_CONTAINER)"
      #  AZURE_BLOB_STORAGE_PROMPTS_CONTAINER: "$(AZURE_BLOB_STORAGE_PROMPTS_CONTAINER)"
      #  AZURE_BLOB_STORAGE_SESSIONS_CONTAINER: "$(AZURE_BLOB_STORAGE_SESSIONS_CONTAINER)"
      #  AZURE_BLOB_STORAGE_VECTORS_CONTAINER: "$(AZURE_BLOB_STORAGE_VECTORS_CONTAINER)"
      #  AZURE_BLOB_STORAGE_CUSTOM_ACTIONS_CONTAINER: "$(AZURE_BLOB_STORAGE_CUSTOM_ACTIONS_CONTAINER)"
      #  AZURE_BLOB_STORAGE_SUBPROMPTS_CONTAINER: "$(AZURE_BLOB_STORAGE_SUBPROMPTS_CONTAINER)"
      #  AZURE_BLOB_MESSAGES_QUEUE_CONTAINER: "$(FILE_SYSTEM_MESSAGES_QUEUE_CONTAINER)"
      #  AZURE_BLOB_STORAGE_MESSAGES_QUEUE_CONTAINER: "$(AZURE_BLOB_STORAGE_MESSAGES_QUEUE_CONTAINER)"

  USER_INTERACTIONS:
    CUSTOM_API:
      {}
      #GENERIC_REST:
      #  PLUGIN_NAME: "generic_rest"
      #  GENERIC_REST_ROUTE_PATH: "/api/get_generic_rest_notification"
      #  GENERIC_REST_ROUTE_METHODS: ["POST"]
      #  GENERIC_REST_BEHAVIOR_PLUGIN_NAME: "im_default_behavior"
      #  GENERIC_REST_MESSAGE_URL: "http://localhost:8000/api/receive_message"
      #  GENERIC_REST_REACTION_URL: "http://localhost:8000/api/receive_message"

    INSTANT_MESSAGING:
      SLACK:
        PLUGIN_NAME: "slack"
        SLACK_BEHAVIOR_PLUGIN_NAME: "im_default_behavior"
        SLACK_ROUTE_PATH: "/api/get_slacknotification"
        SLACK_ROUTE_METHODS: ["POST"]
        SLACK_PLUGIN_DIRECTORY: "plugins.user_interactions.plugins"
        SLACK_MESSAGE_TTL: 3600
        SLACK_SIGNING_SECRET: "$(SLACK_SIGNING_SECRET)"
        SLACK_BOT_TOKEN: "$(SLACK_BOT_TOKEN)"
        SLACK_BOT_USER_TOKEN: "$(SLACK_BOT_USER_TOKEN)"
        SLACK_BOT_USER_ID: "$(SLACK_BOT_USER_ID)"
        SLACK_API_URL: "https://slack.com/api/"
        SLACK_AUTHORIZED_CHANNELS: "$(SLACK_AUTHORIZED_CHANNELS)"
        SLACK_AUTHORIZED_APPS: "$(SLACK_AUTHORIZED_APPS)"
        SLACK_AUTHORIZED_WEBHOOKS: "$(SLACK_AUTHORIZED_WEBHOOKS)"
        SLACK_FEEDBACK_CHANNEL: "$(SLACK_FEEDBACK_CHANNEL)"
        SLACK_FEEDBACK_BOT_ID: "$(SLACK_FEEDBACK_BOT_ID)"
        SLACK_MAX_MESSAGE_LENGTH: 2900
        SLACK_INTERNAL_CHANNEL: "$(SLACK_INTERNAL_CHANNEL)"
        SLACK_WORKSPACE_NAME: "$(SLACK_WORKSPACE_NAME)"
        SLACK_AUTHORIZE_DIRECT_MESSAGE: "$(SLACK_AUTHORIZE_DIRECT_MESSAGE)"

      #TEAMS:
      #PLUGIN_NAME: "teams"
      #  TEAMS_BEHAVIOR_PLUGIN_NAME: "$(TEAMS_BEHAVIOR_PLUGIN_NAME)"
      #  TEAMS_ROUTE_PATH: "$(TEAMS_ROUTE_PATH)"
      #  TEAMS_ROUTE_METHODS: ["$(TEAMS_ROUTE_METHODS)"]
      #  TEAMS_PLUGIN_DIRECTORY: "$(TEAMS_PLUGIN_DIRECTORY)"
      #  TEAMS_MESSAGE_TTL: "$(TEAMS_MESSAGE_TTL)"
      #  TEAMS_SIGNING_SECRET: "$(TEAMS_SIGNING_SECRET)"
      #  TEAMS_BOT_TOKEN: "$(TEAMS_BOT_TOKEN)"
      #  TEAMS_BOT_USER_ID: "$(TEAMS_BOT_USER_ID)"
      #  TEAMS_API_URL: "$(TEAMS_API_URL)"
      #  TEAMS_AUTHORIZED_CHANNELS: "$(TEAMS_AUTHORIZED_CHANNELS)"
      #  TEAMS_AUTHORIZED_APPS: "$(TEAMS_AUTHORIZED_APPS)"
      #  TEAMS_FEEDBACK_CHANNEL: "$(TEAMS_FEEDBACK_CHANNEL)"
      #  TEAMS_FEEDBACK_BOT_ID: "$(TEAMS_FEEDBACK_BOT_ID)"
      #  TEAMS_INTERNAL_CHANNEL: "$(TEAMS_INTERNAL_CHANNEL)"
      #  TEAMS_WORKSPACE_NAME: "$(TEAMS_WORKSPACE_NAME)"

  USER_INTERACTIONS_BEHAVIORS:
    INSTANT_MESSAGING:
      IM_DEFAULT_BEHAVIOR:
        PLUGIN_NAME: "im_default_behavior"

    CUSTOM_API:
      CA_DEFAULT_BEHAVIOR:
        PLUGIN_NAME: "ca_default_behavior"

  GENAI_INTERACTIONS:
    TEXT:
      AZURE_CHATGPT:
        PLUGIN_NAME: "azure_chatgpt"
        AZURE_CHATGPT_INPUT_TOKEN_PRICE: "$(AZURE_CHATGPT_INPUT_TOKEN_PRICE)"
        AZURE_CHATGPT_OUTPUT_TOKEN_PRICE: "$(AZURE_CHATGPT_OUTPUT_TOKEN_PRICE)"
        AZURE_CHATGPT_OPENAI_KEY: "$(AZURE_CHATGPT_OPENAI_KEY)"
        AZURE_CHATGPT_OPENAI_ENDPOINT: "$(AZURE_CHATGPT_OPENAI_ENDPOINT)"
        AZURE_CHATGPT_OPENAI_API_VERSION: "$(AZURE_CHATGPT_OPENAI_API_VERSION)"
        AZURE_CHATGPT_MODEL_NAME: "$(AZURE_CHATGPT_MODEL_NAME)"
        AZURE_CHATGPT_VISION_MODEL_NAME: "$(AZURE_CHATGPT_VISION_MODEL_NAME)"
        AZURE_CHATGPT_IS_ASSISTANT: False
        AZURE_CHATGPT_ASSISTANT_ID: ""

      #AZURE_MISTRAL:
      #  PLUGIN_NAME: "azure_mistral"
      #  AZURE_MISTRAL_ENDPOINT: "$(AZURE_MISTRAL_ENDPOINT)"
      #  AZURE_MISTRAL_INPUT_TOKEN_PRICE: "$(AZURE_MISTRAL_INPUT_TOKEN_PRICE)"
      #  AZURE_MISTRAL_KEY: "$(AZURE_MISTRAL_KEY)"
      #  AZURE_MISTRAL_MODELNAME: "$(AZURE_MISTRAL_MODELNAME)"
      #  AZURE_MISTRAL_OUTPUT_TOKEN_PRICE: "$(AZURE_MISTRAL_OUTPUT_TOKEN_PRICE)"

      #AZURE_LLAMA370B:
      #  PLUGIN_NAME: "azure_llama370b"
      #  AZURE_LLAMA370B_INPUT_TOKEN_PRICE: "$(AZURE_LLAMA370B_INPUT_TOKEN_PRICE)"
      #  AZURE_LLAMA370B_OUTPUT_TOKEN_PRICE: "$(AZURE_LLAMA370B_OUTPUT_TOKEN_PRICE)"
      #  AZURE_LLAMA370B_KEY: "$(AZURE_LLAMA370B_KEY)"
      #  AZURE_LLAMA370B_ENDPOINT: "$(AZURE_LLAMA370B_ENDPOINT)"
      #  AZURE_LLAMA370B_MODELNAME: "$(AZURE_LLAMA370B_MODELNAME)"

      #AZURE_COMMANDR:
      #  PLUGIN_NAME: "azure_commandr"
      #  AZURE_COMMANDR_INPUT_TOKEN_PRICE: "$(AZURE_COMMANDR_INPUT_TOKEN_PRICE)"
      #  AZURE_COMMANDR_OUTPUT_TOKEN_PRICE: "$(AZURE_COMMANDR_OUTPUT_TOKEN_PRICE)"
      #  AZURE_COMMANDR_KEY: "$(AZURE_COMMANDR_KEY)"
      #  AZURE_COMMANDR_ENDPOINT: "$(AZURE_COMMANDR_ENDPOINT)"
      #  AZURE_COMMANDR_MODELNAME: "$(AZURE_COMMANDR_MODELNAME)"

      #VERTEXAI_GEMINI:
      #  PLUGIN_NAME: "vertexai_gemini"
      #  VERTEXAI_GEMINI_INPUT_TOKEN_PRICE: "$(VERTEXAI_GEMINI_INPUT_TOKEN_PRICE)"
      #  VERTEXAI_GEMINI_KEY: "$(VERTEXAI_GEMINI_KEY)"
      #  VERTEXAI_GEMINI_LOCATION: "$(VERTEXAI_GEMINI_LOCATION)"
      #  VERTEXAI_GEMINI_MAX_OUTPUT_TOKENS: "$(VERTEXAI_GEMINI_MAX_OUTPUT_TOKENS)"
      #  VERTEXAI_GEMINI_MODELNAME: "$(VERTEXAI_GEMINI_MODELNAME)"
      #  VERTEXAI_GEMINI_OUTPUT_TOKEN_PRICE: "$(VERTEXAI_GEMINI_OUTPUT_TOKEN_PRICE)"
      #  VERTEXAI_GEMINI_PROJECTNAME: "$(VERTEXAI_GEMINI_PROJECTNAME)"
      #  VERTEXAI_GEMINI_TEMPERATURE: "$(VERTEXAI_GEMINI_TEMPERATURE)"
      #  VERTEXAI_GEMINI_TOP_P: "$(VERTEXAI_GEMINI_TOP_P)"

    IMAGE:
      AZURE_DALLE:
        PLUGIN_NAME: "azure_dalle"
        AZURE_DALLE_INPUT_TOKEN_PRICE: "$(AZURE_DALLE_INPUT_TOKEN_PRICE)"
        AZURE_DALLE_OUTPUT_TOKEN_PRICE: "$(AZURE_DALLE_OUTPUT_TOKEN_PRICE)"
        AZURE_DALLE_OPENAI_KEY: "$(AZURE_DALLE_OPENAI_KEY)"
        AZURE_DALLE_OPENAI_ENDPOINT: "$(AZURE_DALLE_OPENAI_ENDPOINT)"
        AZURE_DALLE_OPENAI_API_VERSION: "$(AZURE_DALLE_OPENAI_API_VERSION)"
        AZURE_DALLE_IMAGE_GENERATOR_MODEL_NAME: "$(AZURE_DALLE_IMAGE_GENERATOR_MODEL_NAME)"

    VECTOR_SEARCH:
      OPENAI_FILE_SEARCH:
        PLUGIN_NAME: "openai_file_search"
        OPENAI_FILE_SEARCH_OPENAI_KEY: "$(OPENAI_FILE_SEARCH_OPENAI_KEY)"
        OPENAI_FILE_SEARCH_OPENAI_ENDPOINT: "$(OPENAI_FILE_SEARCH_OPENAI_ENDPOINT)"
        OPENAI_FILE_SEARCH_OPENAI_API_VERSION: "$(OPENAI_FILE_SEARCH_OPENAI_API_VERSION)"
        OPENAI_FILE_SEARCH_MODEL_HOST: "$(OPENAI_FILE_SEARCH_MODEL_HOST)"
        OPENAI_FILE_SEARCH_MODEL_NAME: "$(OPENAI_FILE_SEARCH_MODEL_NAME)"
        OPENAI_FILE_SEARCH_RESULT_COUNT: "$(OPENAI_FILE_SEARCH_RESULT_COUNT)"
        OPENAI_FILE_SEARCH_INDEX_NAME: "$(OPENAI_FILE_SEARCH_INDEX_NAME)"

      #AZURE_AISEARCH:
      #  PLUGIN_NAME: "azure_aisearch"
      #  AZURE_AISEARCH_AZURE_OPENAI_KEY: "$(AZURE_AISEARCH_AZURE_OPENAI_KEY)"
      #  AZURE_AISEARCH_AZURE_OPENAI_ENDPOINT: "$(AZURE_AISEARCH_AZURE_OPENAI_ENDPOINT)"
      #  AZURE_AISEARCH_OPENAI_API_VERSION: "$(AZURE_AISEARCH_OPENAI_API_VERSION)"
      #  AZURE_AISEARCH_MODEL_NAME: "$(AZURE_AISEARCH_MODEL_NAME)"
      #  AZURE_AISEARCH_SEARCH_ENDPOINT: "$(AZURE_AISEARCH_SEARCH_ENDPOINT)"
      #  AZURE_AISEARCH_KEY: "$(AZURE_AISEARCH_KEY)"
      #  AZURE_AISEARCH_INDEX_NAME: "$(AZURE_AISEARCH_INDEX_NAME)"
      #  AZURE_AISEARCH_TOPN_DOCUMENT: "$(AZURE_AISEARCH_TOPN_DOCUMENT)"
      #  AZURE_AISEARCH_TEXT_COMPLETION_MODEL_NAME: "$(AZURE_AISEARCH_TEXT_COMPLETION_MODEL_NAME)"
      #  AZURE_AISEARCH_PROMPT: "$(AZURE_AISEARCH_PROMPT)"
